package:
  name: datamanager
  version: 0.0.1

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: http://hyounggyu.com/datamanager
  license: GPL

app:
  entry: datamanager
  summary: DataManager
  type: desk
